language: python
python:
  - '3.4'
notifications:
  email:
    on_success: never
    on_failure: always
install:
  - pip install -q -r requirements.txt
  - pip install -q coveralls
script:
  - python setup.py -q nosetests
after_success:
  - coverage run --source=datensparsam setup.py -q nosetests
  - coveralls
