# Python releases to test
language: python
python:
  - "3.4.1"
# Django releases
env:
  - DJANGO_VERSION=Django==1.6.5
# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script:
  - python manage.py test
branches:
  only:
    - master
    - develop
