language: python
python:
  - '3.4'
install:
  - pip install -q -r requirements.txt
  - pip install -q coveralls
script:
  - python setup.py -q nosetests
after_success:
  - coverage run --source=datensparsam setup.py -q nosetests
  - coveralls
  - openssl aes-256-cbc -K $encrypted_ddca671ad439_key -iv $encrypted_ddca671ad439_iv
    -in ssh-key.enc -out ssh-key -d
  - echo -e "Host sculptor.uberspace.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - chmod 600 .travis/ssh-key
  - ssh-add .travis/ssh-key
  - git remote add deploy ssh://dsafe@sculptor.uberspace.de/datensparsam.git
  - git push deploy
