# Python releases to test
language: python
python:
  - "2.7"
# Django releases
env:
  - DJANGO_VERSION=Django==1.5.1
# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors
# command to run tests
script:
  - python manage.py test
branches:
  - master
  - develop
