language: python
python:
  - '3.4'
install:
  - pip install -q -r requirements.txt
  - pip install -q coveralls
script:
  - coverage run --source=datensparsam -q nosetests
after_success:
  - coveralls
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - $DPLOY_HOOK
    on_success: always
    on_failure: never
