language: python
python:
  - "3.4"
env:
  - DJANGO_VERSION=Django==1.6.5
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=datensparsam manage.py test
after_success:
  coveralls
branches:
  only:
    - master
    - develop
