language: python
python:
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  coverage run --source=dtnsprsm manage.py test --failfast
after_success:
  coveralls
notifications:
  email:
    on_success: never
    on_failure: always
  webhooks:
    urls:
      - $DPLOY_HOOK
    on_success: always
    on_failure: never