language: python
python:
  - '3.4'
before_install:
  - openssl aes-256-cbc -K $encrypted_ddca671ad439_key -iv $encrypted_ddca671ad439_iv -in .travis/ssh-key.enc -out ~/.ssh/id_rsa -d
install:
  - pip install -q -r requirements.txt
  - pip install -q coveralls
before_script:
  - echo -e "Host sculptor.uberspace.de\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - python setup.py -q nosetests
after_success:
  # Coveralls.io
  - coverage run --source=datensparsam setup.py -q nosetests
  - coveralls
  # SSH Setup
  - eval `ssh-agent -s`
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
  # Git Config
  - git config --global user.email "dsafe@sculptor.uberspace.de"
  - git config --global user.name "Travis the Build Bot"
  - git config --global push.default matching
  - git remote add deploy ssh://dsafe@sculptor.uberspace.de/datensparsam.git
  - git push deploy
