language: python
python:
  - '3.4'
before_install:
  - openssl aes-256-cbc -K $encrypted_ddca671ad439_key -iv $encrypted_ddca671ad439_iv -in .travis/key.enc -out .travis/key -d
install:
  - pip install -q -r requirements.txt
  - pip install -q coveralls
script:
  - python setup.py -q nosetests
after_success:
  # Coveralls.io
  - coverage run --source=datensparsam setup.py -q nosetests
  - coveralls
  # SSH-Key Setup
  - chmod 600 .travis/key
  - ssh-add .travis/key
  # Git Config
  - git config --global user.email "dsafe@sculptor.uberspace.de"
  - git config --global user.name "Travis the Build Bot"
  - git config --global push.default matching
  - yes | git remote add deploy ssh://dsafe@sculptor.uberspace.de/datensparsam.git
  - yes | git push deploy
